language: python
sudo: false

install:
- pip install tox coveralls

script: tox -v

env:
- TOXENV=lint
- TOXENV=py27
- TOXENV=py34

after_success:
- coveralls

deploy:
  provider: pypi
  user: jonparrott
  distributions: "sdist bdist_wheel"
  password:
    secure: CTvVRvqfSQwiS9hVWD/MA2bU6asT6UuMWevWeBDmsbGr4ug5oT1KB3557iKXQgdvU/BlR+CDwSLRm4i3xexDCkRA/yh6AphthqvBQpAzmRCcnj4VL7mnd0SiF1jBJSmB9m2AK8y6arMuuRT9GMCpcWevLkQG0ExCFxXV+eFJVtbgWs3dO7bF63co2GXUhbLc95HI36X7Z7Zp61FjbztX414srblg7uCUGaMlWUwBai3H0cmexqHsaNyn1fRIW62TCG1d7eL0bgCwp5iNv/KLfJxhFiqUNhYtKzofTAbs9aM0CRGxGO+afGsNKbfDzob4Ekixzt6ieQo6FU30tP2dYaC5JUoFc1zBjY7Ye/1nDNLTWWvB9JRlW9w6fdterBzU8ZB/PYcCWxwDuKBYcuT3RnIDK11RNmpciNMbAHqT/hkxKQiKnTCjsUsKJ39syeh1hsiQFwPZnrlA0hF7u8m96enPKilFzFYO6lTsjHnXKbC9g0bg1yzYechKgCeLp7X7QoWtM9igpT5poIdtA5DdEns7+gWtHu8ZivdXVFL2QU3pTf9ZCDsj93INoS/tGl/yMKWDGlUzXA8TI2zXCgvKjiD0Mr/wtQbhubc1p3HaQz1Sbyr3qyg1Ibmz2uxJTTgjxjV9X3hyLrJcfAIuR26/KvvOZRSHO2RnvGQ33X8A9Io=
  on:
    tags: true
    repo: GoogleCloudPlatform/flask-talisman
